ALTER IGNORE TABLE `#__seminarman_application` ADD `note` DOUBLE AFTER `attendees`;
ALTER IGNORE TABLE `#__seminarman_application` ADD `attendance` INTEGER(11) AFTER `note`;

ALTER IGNORE TABLE `#__seminarman_courses` ADD `email_template_cancel` INTEGER(11) NOT NULL DEFAULT '0' AFTER `email_template`;
ALTER IGNORE TABLE `#__seminarman_courses` ADD `email_template_trainer` INTEGER(11) NOT NULL DEFAULT '0' AFTER `email_template_cancel`;
ALTER IGNORE TABLE `#__seminarman_courses` ADD `email_template_trainer_cancel` INTEGER(11) NOT NULL DEFAULT '0' AFTER `email_template_trainer`;

INSERT IGNORE INTO `#__seminarman_categories` (`id`, `parent_id`, `title`, `alias`, `text`, `meta_keywords`, `meta_description`, `image`, `icon`, `published`, `checked_out`, `checked_out_time`, `access`, `ordering`) VALUES
(1, 0, '1. Klasse (Süd)', '1-klasse-sued', '', '', '', '', '', 1, 0, '0000-00-00 00:00:00', 1, 1);
(2, 0, '1. Klasse (Nord)', '1-klasse-nord', '', '', '', '', '', 1, 0, '0000-00-00 00:00:00', 1, 1);
(3, 0, '2. Klasse', '2-klasse', '', '', '', '', '', 1, 0, '0000-00-00 00:00:00', 1, 1);
(4, 0, '3. Klasse', '3-klasse', '', '', '', '', '', 1, 0, '0000-00-00 00:00:00', 1, 1);
(5, 0, '3. Klasse', '4-klasse', '', '', '', '', '', 1, 0, '0000-00-00 00:00:00', 1, 1);

INSERT IGNORE INTO `#__seminarman_country` (`id`, `loc`, `code`, `title`, `alias`, `description`, `date`, `hits`, `published`, `language`, `checked_out`, `checked_out_time`, `ordering`, `access`, `params`) VALUES
(158, 'CE', 'DE', 'Germany', '', NULL, '0000-00-00 00:00:00', 0, 1, '', 0, '0000-00-00 00:00:00', 23, 0, ''),

INSERT IGNORE INTO `#__seminarman_emailtemplate` (`id`, `templatefor`, `title`, `subject`, `body`, `recipient`, `bcc`, `status`, `isdefault`) VALUES
(1, 0, 'Teilnahmebestätigung für Kurstermin', 'Bibelschule: Kurs "{COURSE_TITLE}" in {CATEGORIES} von {COURSE_START_DATE} bis {COURSE_FINISH_DATE}', '<p>Hallo {NAME},<br />du hast dich für diesen Kurs angemeldet:</p>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Kurs</strong>:</td>\r\n<td>{COURSE_TITLE}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Dozent</strong>:</td>\r\n<td>{TUTOR}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Klasse</strong>:</td>\r\n<td>{CATEGORIES}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Ort</strong>:</td>\r\n<td>{COURSE_LOCATION}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Datum</strong>:</td>\r\n<td>{COURSE_START_DATE} - {COURSE_FINISH_DATE}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p> </p>\r\n<table border="1">\r\n<tbody>\r\n<tr>\r\n<td colspan="2">\r\n<p>Um eine optimale Organisation und Verflegung zu ermöglichen, bitte die Teilnahme an dem Kurstermin durch Klicken auf diese Links verbindlich zu bestätigen oder zu stornieren.</p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td><a href="{PRESENCE_LINK}">Teilnahme bestätigen</a></td>\r\n<td><a href="{ABSENCE_LINK}">Teilname stornieren</a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p> </p>\r\n<p>{COURSE_INTROTEXT}</p>\r\n<p> </p>\r\n<p>Weitere Informationen, findest du auf unserer Webseite.</p>\r\n<p> </p>\r\n<p>Gottes Segen,</p>\r\n<p>Bibelschule Stephanus</p>', '{EMAIL}', '{ADMIN_CUSTOM_RECIPIENT}', NULL, 0),
(2, 2, 'Teilnehmerliste für Kurstermin', 'Bibelschule: Teilnehmerliste für Kurs "{COURSE_TITLE}"', '<p>Hallo {NAME},</p>\r\n<p>im Anhang ist die aktuelle Teilnehmerliste für deinen Kurs '{COURSE_TITLE}'.</p>\r\n<p>In der Liste sind alle Stundenten eingetragen, die zu der Klasse gehören, sowie evtl. Studenten aus höheren Klassen, die auch an dem Fach teilnehmen möchten. Außerdem wurden die Studenten aufgefordert derren Teilnahme zu bestätigen bzw. (falls verhindert) zu stornieren. Dieser Status ist in der Liste jeweils pro Student sowie ingesammt aufsummiert (bestätigt/alle) ersichtlich. </p>\r\n<p>Bitte vor dem Unterricht ausdrucken und von den anwesenden Studenten unterschreiben und die Anwesenheit in Stunden eintragen lassen.</p>\r\n<p>Nach dem Kurs bitte die Liste eingescannt (als pdf, tif, jpg oder png) an info@bibelschule-stephanus.de schicken. Die Anwesenheiten werden dann in das System eingepflegt und die Liste archiviert.</p>\r\n<p> </p>\r\n<p>Folgende Informationen über den Kurs haben die Studenten per Email empfangen.</p>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Kurs</strong>:</td>\r\n<td>{COURSE_TITLE}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Dozent</strong>:</td>\r\n<td>{TUTOR}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Klasse</strong>:</td>\r\n<td>{CATEGORIES}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Ort</strong>:</td>\r\n<td>{COURSE_LOCATION}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Datum</strong>:</td>\r\n<td>{COURSE_START_DATE} - {COURSE_FINISH_DATE}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p> </p>\r\n<p>{COURSE_INTROTEXT}</p>\r\n<p> </p>\r\n<p>Gottes Segen,</p>\r\n<p>Bibelschule Stephanus</p>', '{EMAIL}', '{ADMIN_CUSTOM_RECIPIENT}', NULL, 1);
(3, 3, 'Schüler: Kurs abgesagt', 'Bibelschule: ABSAGE des Kurses "{COURSE_TITLE}" von {COURSE_START_DATE} bis {COURSE_FINISH_DATE}', '<p>Hallo {NAME},<br />dieser Kurs wurde abgesagt und findet nicht statt:</p>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Kurs</strong>:</td>\r\n<td>{COURSE_TITLE}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Dozent</strong>:</td>\r\n<td>{TUTOR}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Klasse</strong>:</td>\r\n<td>{CATEGORIES}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Ort</strong>:</td>\r\n<td>{COURSE_LOCATION}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Datum</strong>:</td>\r\n<td>{COURSE_START_DATE} - {COURSE_FINISH_DATE}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span style="font-size: 13px;">Weitere Informationen, findest du auf unserer Webseite.</span></p>\r\n<p> </p>\r\n<p>Gottes Segen,</p>\r\n<p>Bibelschule Stephanus</p>', '{EMAIL}', '{ADMIN_CUSTOM_RECIPIENT}', NULL, 1);
(4, 4, 'Dozent: Kurs abgesagt', 'Bibelschule: ABSAGE des Kurses "{COURSE_TITLE}" von {COURSE_START_DATE} bis {COURSE_FINISH_DATE}', '<p>Hallo {NAME},<br />dieser Kurs wurde abgesagt und findet nicht statt:</p>\r\n<table>\r\n<tbody>\r\n<tr>\r\n<td><strong>Kurs</strong>:</td>\r\n<td>{COURSE_TITLE}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Dozent</strong>:</td>\r\n<td>{TUTOR}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Klasse</strong>:</td>\r\n<td>{CATEGORIES}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Ort</strong>:</td>\r\n<td>{COURSE_LOCATION}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Datum</strong>:</td>\r\n<td>{COURSE_START_DATE} - {COURSE_FINISH_DATE}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p><span style="font-size: 13px;">Weitere Informationen, findest du auf unserer Webseite.</span></p>\r\n<p> </p>\r\n<p>Gottes Segen,</p>\r\n<p>Bibelschule Stephanus</p>', '{EMAIL}', '{ADMIN_CUSTOM_RECIPIENT}', NULL, 1);

INSERT IGNORE INTO `#__seminarman_pdftemplate` (`id`, `templatefor`, `name`, `html`, `srcpdf`, `isdefault`, `margin_left`, `margin_right`, `margin_top`, `margin_bottom`, `paperformat`, `orientation`) VALUES
(1, 0, 'Rechnungsvorlage', '<p>{CUSTOM_COMPANY}<br />{TITLE}{FIRSTNAME} {LASTNAME}<br /> {CUSTOM_STREET}<br /> {CUSTOM_ZIP} {CUSTOM_CITY}</p>\r\n<p> </p>\r\n<p> </p>\r\n<p style="text-align: right;"><strong>Datum</strong> {INVOICE_DATE}</p>\r\n<p> </p>\r\n<p><span style="font-size: x-large;"><strong>Ihre Rechnung {INVOICE_NUMBER}</strong></span></p>\r\n<p> </p>\r\n<table style="width: 100%; font-size: small;" border="1" cellpadding="5" align="center">\r\n<tbody>\r\n<tr>\r\n<td style="width: 10%; text-align: left;">Pos.</td>\r\n<td style="width: 10%; text-align: left;">Menge</td>\r\n<td style="width: 50%; text-align: left;">Text</td>\r\n<td style="width: 15%; text-align: right;">Einzelpreis EUR</td>\r\n<td style="width: 15%; text-align: right;">Gesamtpreis EUR</td>\r\n</tr>\r\n<tr>\r\n<td style="text-align: left;">1</td>\r\n<td style="text-align: left;">{ATTENDEES}</td>\r\n<td style="text-align: left;">{COURSE_TITLE}<br />Kursnummer: {COURSE_CODE}<br />Vom {COURSE_START_DATE} bis {COURSE_FINISH_DATE} in {COURSE_LOCATION}</td>\r\n<td style="text-align: right;">{PRICE_PER_ATTENDEE}</td>\r\n<td style="text-align: right;">{PRICE_TOTAL}</td>\r\n</tr>\r\n<tr>\r\n<td style="text-align: right;" colspan="3">Gesamt Netto</td>\r\n<td style="text-align: right;" colspan="2">{PRICE_TOTAL}</td>\r\n</tr>\r\n<tr>\r\n<td style="text-align: right;" colspan="3">zzgl. {PRICE_VAT_PERCENT}% MwSt.</td>\r\n<td style="text-align: right;" colspan="2">{PRICE_VAT} </td>\r\n</tr>\r\n<tr>\r\n<td style="text-align: right;" colspan="3"><strong>Gesamtbetrag</strong></td>\r\n<td style="text-align: right;" colspan="2"><strong>{PRICE_TOTAL_VAT}</strong></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p> </p>\r\n<p>Der Betrag muss 3 Werktage vor Kursbeginn auf unser Konto eingegangen sein.</p>\r\n<p></p>', '', 1, 20, 20, 70, 20, 'A4', 'P'),
(2, 0, 'Test aller Felder', '<ul>\r\n<li>{INVOICE_NUMBER}: Rechnungsnummer</li>\r\n<li>{INVOICE_DATE}: Rechnungsdatum</li>\r\n<li>{ATTENDEES}: Anzahl Teilnehmer</li>\r\n<li>{SALUTATION}: Anrede</li>\r\n<li>{TITLE}: Titel</li>\r\n<li>{FIRSTNAME}: Vorname</li>\r\n<li>{LASTNAME}: Nachname</li>\r\n<li>{EMAIL}: E-Mail</li>\r\n<li>{CUSTOM_COMPANY}: Firma/Organisation</li>\r\n<li>{CUSTOM_STREET}: Strasse</li>\r\n<li>{CUSTOM_ZIP}: PLZ</li>\r\n<li>{CUSTOM_CITY}: Ort</li>\r\n<li>{CUSTOM_COUNTRY}: Land</li>\r\n<li>{CUSTOM_PHONE}: Telefon</li>\r\n<li>{COURSE_TITLE}: Kurstitel</li>\r\n<li>{COURSE_CODE}: Kursnr.</li>\r\n<li>{COURSE_CAPACITY}: Kapazität</li>\r\n<li>{COURSE_LOCATION}: Ort</li>\r\n<li>{COURSE_URL}: URL</li>\r\n<li>{COURSE_START_DATE}: Beginn</li>\r\n<li>{COURSE_FINISH_DATE}: Ende</li>\r\n<li>{PRICE_PER_ATTENDEE}: Preis pro Teilnehmer</li>\r\n<li>{PRICE_PER_ATTENDEE_VAT}: Preis pro Teilnehmer inkl. Steuern</li>\r\n<li>{PRICE_TOTAL}: Gesamtpreis</li>\r\n<li>{PRICE_TOTAL_VAT}: Gesamtpreis inkl. Steuern</li>\r\n<li>{PRICE_VAT_PERCENT}: Mwst. Satz</li>\r\n<li>{PRICE_VAT}: Mwst. Betrag</li>\r\n<li>{TUTOR_FIRSTNAME}: Vorname</li>\r\n<li>{TUTOR_LASTNAME}: Nachname</li>\r\n<li>{GROUP}: Gruppe</li>\r\n<li>{EXPERIENCE_LEVEL}: Erfahrungslevel</li>\r\n</ul>', '', 0, 0, 0, 0, 0, 'A4', 'P'),
(4, 1, 'Teilnehmerliste 1', '<table style="width: 100%;" cellspacing="0" cellpadding="0">\r\n<tbody>\r\n<tr>\r\n<td style="width: 7%;"><strong>Kurs</strong></td>\r\n<td style="width: 28%;">{COURSE_TITLE}</td>\r\n<td style="width: 7%;"><strong>Ort</strong></td>\r\n<td style="width: 29%;">{COURSE_LOCATION}</td>\r\n<td style="width: 10%;"><strong>Dozent</strong></td>\r\n<td style="width: 20%;">{TUTOR}</td>\r\n</tr>\r\n<tr>\r\n<td><strong>Datum</strong></td>\r\n<td>{COURSE_START_DATE} - {COURSE_FINISH_DATE}</td>\r\n<td><strong>Klasse</strong></td>\r\n<td>{CATEGORIES}</td>\r\n<td><strong>Stand</strong></td>\r\n<td>{CURRENT_DATE} {ATTENDEES_STATUS_1}/{ATTENDEES}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<table style="width: 100%;" border="1">\r\n<tbody>\r\n<tr><th style="width: 20%; text-align: left;"><span style="color: #000080;"><strong>Name</strong></span></th><th style="width: 20%; text-align: left;"><span style="color: #000080;"><strong>Vorname</strong></span></th><th style="width: 20%; text-align: left;"><span style="color: #000080;"><strong>Teilnahmestatus</strong></span></th><th style="width: 40%; text-align: left;" colspan="2"><span style="color: #000080;"><strong>Anwenheit in Std./Unterschrift</strong></span></th></tr>\r\n<tr class="{LOOP}">\r\n<td style="text-align: left;">{LASTNAME}</td>\r\n<td style="text-align: left;">{FIRSTNAME}</td>\r\n<td style="text-align: left;">{STATUS}</td>\r\n<td style="width: 10%; text-align: left;">{ANWESENHEIT}</td>\r\n<td style="width: 30%;"> </td>\r\n</tr>\r\n</tbody>\r\n</table>', '', 1, 10, 10, 15, 15, 'A4', 'P');
